// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"goods/goods"
	"goods/internal/logic"
	"goods/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) Ping(ctx context.Context, in *goods.Request) (*goods.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *GoodsServer) GetGoodsByIDs(ctx context.Context, in *goods.GetGoodsByIDsRequest) (*goods.GetGoodsByIDsResponse, error) {
	l := logic.NewGetGoodsByIDsLogic(ctx, s.svcCtx)
	return l.GetGoodsByIDs(in)
}

func (s *GoodsServer) UpdateGoodsStocks(ctx context.Context, in *goods.UpdateGoodsStocksRequest) (*goods.UpdateGoodsStocksResponse, error) {
	l := logic.NewUpdateGoodsStocksLogic(ctx, s.svcCtx)
	return l.UpdateGoodsStocks(in)
}

func (s *GoodsServer) UpdateGoodsStocksRollback(ctx context.Context, in *goods.UpdateGoodsStocksRollbackRequest) (*goods.UpdateGoodsStocksRollbackResponse, error) {
	l := logic.NewUpdateGoodsStocksRollbackLogic(ctx, s.svcCtx)
	return l.UpdateGoodsStocksRollback(in)
}

// TCC
func (s *GoodsServer) TCCTradingNum(ctx context.Context, in *goods.TCCTradingNumRequest) (*goods.TCCTradingNumResponse, error) {
	l := logic.NewTCCTradingNumLogic(ctx, s.svcCtx)
	return l.TCCTradingNum(in)
}

func (s *GoodsServer) TCCTradingLockNum(ctx context.Context, in *goods.TCCTradingLockNumRequest) (*goods.TCCTradingLockNumResponse, error) {
	l := logic.NewTCCTradingLockNumLogic(ctx, s.svcCtx)
	return l.TCCTradingLockNum(in)
}

func (s *GoodsServer) TCCTradingRollbackNum(ctx context.Context, in *goods.TCCTradingRollbackNumRequest) (*goods.TCCTradingRollbackNumResponse, error) {
	l := logic.NewTCCTradingRollbackNumLogic(ctx, s.svcCtx)
	return l.TCCTradingRollbackNum(in)
}
