// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Order_Ping_FullMethodName                    = "/order.Order/Ping"
	Order_CreateOrder_FullMethodName             = "/order.Order/CreateOrder"
	Order_GetOrderRollback_FullMethodName        = "/order.Order/GetOrderRollback"
	Order_GetOrder_FullMethodName                = "/order.Order/GetOrder"
	Order_UpdateOrder_FullMethodName             = "/order.Order/UpdateOrder"
	Order_CreateOrderGoods_FullMethodName        = "/order.Order/CreateOrderGoods"
	Order_GetOrderGoodsByOrderID_FullMethodName  = "/order.Order/GetOrderGoodsByOrderID"
	Order_TCCTradingOrder_FullMethodName         = "/order.Order/TCCTradingOrder"
	Order_TCCTradingLockOrder_FullMethodName     = "/order.Order/TCCTradingLockOrder"
	Order_TCCTradingRollbackOrder_FullMethodName = "/order.Order/TCCTradingRollbackOrder"
)

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetOrderRollback(ctx context.Context, in *GetOrderRollbackRequest, opts ...grpc.CallOption) (*GetOrderRollbackResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error)
	CreateOrderGoods(ctx context.Context, in *CreateOrderGoodsRequest, opts ...grpc.CallOption) (*CreateOrderGoodsResponse, error)
	GetOrderGoodsByOrderID(ctx context.Context, in *GetOrderGoodsByOrderIDRequest, opts ...grpc.CallOption) (*GetOrderGoodsByOrderIDResponse, error)
	// TCC
	TCCTradingOrder(ctx context.Context, in *TCCTradingOrderRequest, opts ...grpc.CallOption) (*TCCTradingOrderResponse, error)
	TCCTradingLockOrder(ctx context.Context, in *TCCTradingLockOrderRequest, opts ...grpc.CallOption) (*TCCTradingLockOrderResponse, error)
	TCCTradingRollbackOrder(ctx context.Context, in *TCCTradingRollbackOrderRequest, opts ...grpc.CallOption) (*TCCTradingRollbackOrderResponse, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Order_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, Order_CreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrderRollback(ctx context.Context, in *GetOrderRollbackRequest, opts ...grpc.CallOption) (*GetOrderRollbackResponse, error) {
	out := new(GetOrderRollbackResponse)
	err := c.cc.Invoke(ctx, Order_GetOrderRollback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, Order_GetOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error) {
	out := new(UpdateOrderResponse)
	err := c.cc.Invoke(ctx, Order_UpdateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrderGoods(ctx context.Context, in *CreateOrderGoodsRequest, opts ...grpc.CallOption) (*CreateOrderGoodsResponse, error) {
	out := new(CreateOrderGoodsResponse)
	err := c.cc.Invoke(ctx, Order_CreateOrderGoods_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrderGoodsByOrderID(ctx context.Context, in *GetOrderGoodsByOrderIDRequest, opts ...grpc.CallOption) (*GetOrderGoodsByOrderIDResponse, error) {
	out := new(GetOrderGoodsByOrderIDResponse)
	err := c.cc.Invoke(ctx, Order_GetOrderGoodsByOrderID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TCCTradingOrder(ctx context.Context, in *TCCTradingOrderRequest, opts ...grpc.CallOption) (*TCCTradingOrderResponse, error) {
	out := new(TCCTradingOrderResponse)
	err := c.cc.Invoke(ctx, Order_TCCTradingOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TCCTradingLockOrder(ctx context.Context, in *TCCTradingLockOrderRequest, opts ...grpc.CallOption) (*TCCTradingLockOrderResponse, error) {
	out := new(TCCTradingLockOrderResponse)
	err := c.cc.Invoke(ctx, Order_TCCTradingLockOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) TCCTradingRollbackOrder(ctx context.Context, in *TCCTradingRollbackOrderRequest, opts ...grpc.CallOption) (*TCCTradingRollbackOrderResponse, error) {
	out := new(TCCTradingRollbackOrderResponse)
	err := c.cc.Invoke(ctx, Order_TCCTradingRollbackOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility
type OrderServer interface {
	Ping(context.Context, *Request) (*Response, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrderRollback(context.Context, *GetOrderRollbackRequest) (*GetOrderRollbackResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	UpdateOrder(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error)
	CreateOrderGoods(context.Context, *CreateOrderGoodsRequest) (*CreateOrderGoodsResponse, error)
	GetOrderGoodsByOrderID(context.Context, *GetOrderGoodsByOrderIDRequest) (*GetOrderGoodsByOrderIDResponse, error)
	// TCC
	TCCTradingOrder(context.Context, *TCCTradingOrderRequest) (*TCCTradingOrderResponse, error)
	TCCTradingLockOrder(context.Context, *TCCTradingLockOrderRequest) (*TCCTradingLockOrderResponse, error)
	TCCTradingRollbackOrder(context.Context, *TCCTradingRollbackOrderRequest) (*TCCTradingRollbackOrderResponse, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (UnimplementedOrderServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOrderServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServer) GetOrderRollback(context.Context, *GetOrderRollbackRequest) (*GetOrderRollbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderRollback not implemented")
}
func (UnimplementedOrderServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderServer) UpdateOrder(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedOrderServer) CreateOrderGoods(context.Context, *CreateOrderGoodsRequest) (*CreateOrderGoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderGoods not implemented")
}
func (UnimplementedOrderServer) GetOrderGoodsByOrderID(context.Context, *GetOrderGoodsByOrderIDRequest) (*GetOrderGoodsByOrderIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderGoodsByOrderID not implemented")
}
func (UnimplementedOrderServer) TCCTradingOrder(context.Context, *TCCTradingOrderRequest) (*TCCTradingOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TCCTradingOrder not implemented")
}
func (UnimplementedOrderServer) TCCTradingLockOrder(context.Context, *TCCTradingLockOrderRequest) (*TCCTradingLockOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TCCTradingLockOrder not implemented")
}
func (UnimplementedOrderServer) TCCTradingRollbackOrder(context.Context, *TCCTradingRollbackOrderRequest) (*TCCTradingRollbackOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TCCTradingRollbackOrder not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrderRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetOrderRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderRollback(ctx, req.(*GetOrderRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrderGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrderGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateOrderGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrderGoods(ctx, req.(*CreateOrderGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrderGoodsByOrderID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderGoodsByOrderIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderGoodsByOrderID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetOrderGoodsByOrderID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderGoodsByOrderID(ctx, req.(*GetOrderGoodsByOrderIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TCCTradingOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TCCTradingOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TCCTradingOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_TCCTradingOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TCCTradingOrder(ctx, req.(*TCCTradingOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TCCTradingLockOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TCCTradingLockOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TCCTradingLockOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_TCCTradingLockOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TCCTradingLockOrder(ctx, req.(*TCCTradingLockOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_TCCTradingRollbackOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TCCTradingRollbackOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).TCCTradingRollbackOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_TCCTradingRollbackOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).TCCTradingRollbackOrder(ctx, req.(*TCCTradingRollbackOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Order_Ping_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrderRollback",
			Handler:    _Order_GetOrderRollback_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _Order_GetOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _Order_UpdateOrder_Handler,
		},
		{
			MethodName: "CreateOrderGoods",
			Handler:    _Order_CreateOrderGoods_Handler,
		},
		{
			MethodName: "GetOrderGoodsByOrderID",
			Handler:    _Order_GetOrderGoodsByOrderID_Handler,
		},
		{
			MethodName: "TCCTradingOrder",
			Handler:    _Order_TCCTradingOrder_Handler,
		},
		{
			MethodName: "TCCTradingLockOrder",
			Handler:    _Order_TCCTradingLockOrder_Handler,
		},
		{
			MethodName: "TCCTradingRollbackOrder",
			Handler:    _Order_TCCTradingRollbackOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
