// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: goods.proto

package goods

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type GoodsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int64  `protobuf:"varint,10,opt,name=ID,proto3" json:"ID,omitempty"`
	Name  string `protobuf:"bytes,20,opt,name=Name,proto3" json:"Name,omitempty"`
	Price string `protobuf:"bytes,30,opt,name=Price,proto3" json:"Price,omitempty"`
	Stock int64  `protobuf:"varint,40,opt,name=Stock,proto3" json:"Stock,omitempty"`
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsInfo) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GoodsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfo) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GoodsInfo) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GetGoodsByIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDs []int64 `protobuf:"varint,10,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
}

func (x *GetGoodsByIDsRequest) Reset() {
	*x = GetGoodsByIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIDsRequest) ProtoMessage() {}

func (x *GetGoodsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoodsByIDsRequest) GetIDs() []int64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type GetGoodsByIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*GoodsInfo `protobuf:"bytes,10,rep,name=Infos,proto3" json:"Infos,omitempty"`
}

func (x *GetGoodsByIDsResponse) Reset() {
	*x = GetGoodsByIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIDsResponse) ProtoMessage() {}

func (x *GetGoodsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetGoodsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{4}
}

func (x *GetGoodsByIDsResponse) GetInfos() []*GoodsInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type UpdateStockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  int64 `protobuf:"varint,10,opt,name=ID,proto3" json:"ID,omitempty"`
	Num int64 `protobuf:"varint,20,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *UpdateStockReq) Reset() {
	*x = UpdateStockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockReq) ProtoMessage() {}

func (x *UpdateStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockReq.ProtoReflect.Descriptor instead.
func (*UpdateStockReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStockReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateStockReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UpdateGoodsStocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfos []*UpdateStockReq `protobuf:"bytes,10,rep,name=GoodsInfos,proto3" json:"GoodsInfos,omitempty"`
}

func (x *UpdateGoodsStocksRequest) Reset() {
	*x = UpdateGoodsStocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGoodsStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsStocksRequest) ProtoMessage() {}

func (x *UpdateGoodsStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsStocksRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoodsStocksRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGoodsStocksRequest) GetGoodsInfos() []*UpdateStockReq {
	if x != nil {
		return x.GoodsInfos
	}
	return nil
}

type UpdateGoodsStocksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*GoodsInfo `protobuf:"bytes,10,rep,name=Infos,proto3" json:"Infos,omitempty"`
}

func (x *UpdateGoodsStocksResponse) Reset() {
	*x = UpdateGoodsStocksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGoodsStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsStocksResponse) ProtoMessage() {}

func (x *UpdateGoodsStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsStocksResponse.ProtoReflect.Descriptor instead.
func (*UpdateGoodsStocksResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGoodsStocksResponse) GetInfos() []*GoodsInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type UpdateGoodsStocksRollbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfos []*UpdateStockReq `protobuf:"bytes,10,rep,name=GoodsInfos,proto3" json:"GoodsInfos,omitempty"`
}

func (x *UpdateGoodsStocksRollbackRequest) Reset() {
	*x = UpdateGoodsStocksRollbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGoodsStocksRollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsStocksRollbackRequest) ProtoMessage() {}

func (x *UpdateGoodsStocksRollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsStocksRollbackRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoodsStocksRollbackRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGoodsStocksRollbackRequest) GetGoodsInfos() []*UpdateStockReq {
	if x != nil {
		return x.GoodsInfos
	}
	return nil
}

type UpdateGoodsStocksRollbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*GoodsInfo `protobuf:"bytes,10,rep,name=Infos,proto3" json:"Infos,omitempty"`
}

func (x *UpdateGoodsStocksRollbackResponse) Reset() {
	*x = UpdateGoodsStocksRollbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGoodsStocksRollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsStocksRollbackResponse) ProtoMessage() {}

func (x *UpdateGoodsStocksRollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsStocksRollbackResponse.ProtoReflect.Descriptor instead.
func (*UpdateGoodsStocksRollbackResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateGoodsStocksRollbackResponse) GetInfos() []*GoodsInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// TCC
type TCCInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  int64 `protobuf:"varint,10,opt,name=ID,proto3" json:"ID,omitempty"`
	Num int64 `protobuf:"varint,20,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *TCCInfo) Reset() {
	*x = TCCInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCCInfo) ProtoMessage() {}

func (x *TCCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCCInfo.ProtoReflect.Descriptor instead.
func (*TCCInfo) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{10}
}

func (x *TCCInfo) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TCCInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type TCCTradingNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradingNum []*TCCInfo `protobuf:"bytes,10,rep,name=TradingNum,proto3" json:"TradingNum,omitempty"`
}

func (x *TCCTradingNumRequest) Reset() {
	*x = TCCTradingNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCCTradingNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCCTradingNumRequest) ProtoMessage() {}

func (x *TCCTradingNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCCTradingNumRequest.ProtoReflect.Descriptor instead.
func (*TCCTradingNumRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{11}
}

func (x *TCCTradingNumRequest) GetTradingNum() []*TCCInfo {
	if x != nil {
		return x.TradingNum
	}
	return nil
}

type TCCTradingNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradingNum []*TCCInfo `protobuf:"bytes,10,rep,name=TradingNum,proto3" json:"TradingNum,omitempty"`
}

func (x *TCCTradingNumResponse) Reset() {
	*x = TCCTradingNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCCTradingNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCCTradingNumResponse) ProtoMessage() {}

func (x *TCCTradingNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCCTradingNumResponse.ProtoReflect.Descriptor instead.
func (*TCCTradingNumResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{12}
}

func (x *TCCTradingNumResponse) GetTradingNum() []*TCCInfo {
	if x != nil {
		return x.TradingNum
	}
	return nil
}

type TCCTradingLockNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradingNum []*TCCInfo `protobuf:"bytes,10,rep,name=TradingNum,proto3" json:"TradingNum,omitempty"`
}

func (x *TCCTradingLockNumRequest) Reset() {
	*x = TCCTradingLockNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCCTradingLockNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCCTradingLockNumRequest) ProtoMessage() {}

func (x *TCCTradingLockNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCCTradingLockNumRequest.ProtoReflect.Descriptor instead.
func (*TCCTradingLockNumRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{13}
}

func (x *TCCTradingLockNumRequest) GetTradingNum() []*TCCInfo {
	if x != nil {
		return x.TradingNum
	}
	return nil
}

type TCCTradingLockNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradingNum []*TCCInfo `protobuf:"bytes,10,rep,name=TradingNum,proto3" json:"TradingNum,omitempty"`
}

func (x *TCCTradingLockNumResponse) Reset() {
	*x = TCCTradingLockNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCCTradingLockNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCCTradingLockNumResponse) ProtoMessage() {}

func (x *TCCTradingLockNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCCTradingLockNumResponse.ProtoReflect.Descriptor instead.
func (*TCCTradingLockNumResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{14}
}

func (x *TCCTradingLockNumResponse) GetTradingNum() []*TCCInfo {
	if x != nil {
		return x.TradingNum
	}
	return nil
}

type TCCTradingRollbackNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradingNum []*TCCInfo `protobuf:"bytes,10,rep,name=TradingNum,proto3" json:"TradingNum,omitempty"`
}

func (x *TCCTradingRollbackNumRequest) Reset() {
	*x = TCCTradingRollbackNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCCTradingRollbackNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCCTradingRollbackNumRequest) ProtoMessage() {}

func (x *TCCTradingRollbackNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCCTradingRollbackNumRequest.ProtoReflect.Descriptor instead.
func (*TCCTradingRollbackNumRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{15}
}

func (x *TCCTradingRollbackNumRequest) GetTradingNum() []*TCCInfo {
	if x != nil {
		return x.TradingNum
	}
	return nil
}

type TCCTradingRollbackNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradingNum []*TCCInfo `protobuf:"bytes,10,rep,name=TradingNum,proto3" json:"TradingNum,omitempty"`
}

func (x *TCCTradingRollbackNumResponse) Reset() {
	*x = TCCTradingRollbackNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCCTradingRollbackNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCCTradingRollbackNumResponse) ProtoMessage() {}

func (x *TCCTradingRollbackNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCCTradingRollbackNumResponse.ProtoReflect.Descriptor instead.
func (*TCCTradingRollbackNumResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{16}
}

func (x *TCCTradingRollbackNumResponse) GetTradingNum() []*TCCInfo {
	if x != nil {
		return x.TradingNum
	}
	return nil
}

var File_goods_proto protoreflect.FileDescriptor

var file_goods_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x69, 0x6e, 0x67, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x6f, 0x6e, 0x67, 0x22, 0x5b, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x1e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x18, 0x28, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x44,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x44, 0x73, 0x18,
	0x0a, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x49, 0x44, 0x73, 0x22, 0x3f, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x32, 0x0a, 0x0e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x4e, 0x75, 0x6d, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22,
	0x51, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x22, 0x43, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x59, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x6f, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x22, 0x4b, 0x0a, 0x21, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22,
	0x2b, 0x0a, 0x07, 0x54, 0x43, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75,
	0x6d, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x46, 0x0a, 0x14,
	0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4e,
	0x75, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x2e, 0x54, 0x43, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x4e, 0x75, 0x6d, 0x22, 0x47, 0x0a, 0x15, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x0a, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x22, 0x4a, 0x0a,
	0x18, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x6b, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x54, 0x72, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x54,
	0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x22, 0x4b, 0x0a, 0x19, 0x54, 0x43, 0x43,
	0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x54, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x22, 0x4e, 0x0a, 0x1c, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x54, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x22, 0x4f, 0x0a, 0x1d, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x54, 0x72, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x32, 0xcc, 0x04, 0x0a, 0x05, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x12, 0x27, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x2e, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x12, 0x1b, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x44,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e,
	0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x73, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x27, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a,
	0x0a, 0x0d, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x12,
	0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x54, 0x43,
	0x43, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x62, 0x0a, 0x15, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x23, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x54, 0x43, 0x43, 0x54, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goods_proto_rawDescOnce sync.Once
	file_goods_proto_rawDescData = file_goods_proto_rawDesc
)

func file_goods_proto_rawDescGZIP() []byte {
	file_goods_proto_rawDescOnce.Do(func() {
		file_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_proto_rawDescData)
	})
	return file_goods_proto_rawDescData
}

var file_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_goods_proto_goTypes = []interface{}{
	(*Request)(nil),                           // 0: goods.Request
	(*Response)(nil),                          // 1: goods.Response
	(*GoodsInfo)(nil),                         // 2: goods.GoodsInfo
	(*GetGoodsByIDsRequest)(nil),              // 3: goods.GetGoodsByIDsRequest
	(*GetGoodsByIDsResponse)(nil),             // 4: goods.GetGoodsByIDsResponse
	(*UpdateStockReq)(nil),                    // 5: goods.UpdateStockReq
	(*UpdateGoodsStocksRequest)(nil),          // 6: goods.UpdateGoodsStocksRequest
	(*UpdateGoodsStocksResponse)(nil),         // 7: goods.UpdateGoodsStocksResponse
	(*UpdateGoodsStocksRollbackRequest)(nil),  // 8: goods.UpdateGoodsStocksRollbackRequest
	(*UpdateGoodsStocksRollbackResponse)(nil), // 9: goods.UpdateGoodsStocksRollbackResponse
	(*TCCInfo)(nil),                           // 10: goods.TCCInfo
	(*TCCTradingNumRequest)(nil),              // 11: goods.TCCTradingNumRequest
	(*TCCTradingNumResponse)(nil),             // 12: goods.TCCTradingNumResponse
	(*TCCTradingLockNumRequest)(nil),          // 13: goods.TCCTradingLockNumRequest
	(*TCCTradingLockNumResponse)(nil),         // 14: goods.TCCTradingLockNumResponse
	(*TCCTradingRollbackNumRequest)(nil),      // 15: goods.TCCTradingRollbackNumRequest
	(*TCCTradingRollbackNumResponse)(nil),     // 16: goods.TCCTradingRollbackNumResponse
}
var file_goods_proto_depIdxs = []int32{
	2,  // 0: goods.GetGoodsByIDsResponse.Infos:type_name -> goods.GoodsInfo
	5,  // 1: goods.UpdateGoodsStocksRequest.GoodsInfos:type_name -> goods.UpdateStockReq
	2,  // 2: goods.UpdateGoodsStocksResponse.Infos:type_name -> goods.GoodsInfo
	5,  // 3: goods.UpdateGoodsStocksRollbackRequest.GoodsInfos:type_name -> goods.UpdateStockReq
	2,  // 4: goods.UpdateGoodsStocksRollbackResponse.Infos:type_name -> goods.GoodsInfo
	10, // 5: goods.TCCTradingNumRequest.TradingNum:type_name -> goods.TCCInfo
	10, // 6: goods.TCCTradingNumResponse.TradingNum:type_name -> goods.TCCInfo
	10, // 7: goods.TCCTradingLockNumRequest.TradingNum:type_name -> goods.TCCInfo
	10, // 8: goods.TCCTradingLockNumResponse.TradingNum:type_name -> goods.TCCInfo
	10, // 9: goods.TCCTradingRollbackNumRequest.TradingNum:type_name -> goods.TCCInfo
	10, // 10: goods.TCCTradingRollbackNumResponse.TradingNum:type_name -> goods.TCCInfo
	0,  // 11: goods.Goods.Ping:input_type -> goods.Request
	3,  // 12: goods.Goods.GetGoodsByIDs:input_type -> goods.GetGoodsByIDsRequest
	6,  // 13: goods.Goods.UpdateGoodsStocks:input_type -> goods.UpdateGoodsStocksRequest
	8,  // 14: goods.Goods.UpdateGoodsStocksRollback:input_type -> goods.UpdateGoodsStocksRollbackRequest
	11, // 15: goods.Goods.TCCTradingNum:input_type -> goods.TCCTradingNumRequest
	13, // 16: goods.Goods.TCCTradingLockNum:input_type -> goods.TCCTradingLockNumRequest
	15, // 17: goods.Goods.TCCTradingRollbackNum:input_type -> goods.TCCTradingRollbackNumRequest
	1,  // 18: goods.Goods.Ping:output_type -> goods.Response
	4,  // 19: goods.Goods.GetGoodsByIDs:output_type -> goods.GetGoodsByIDsResponse
	7,  // 20: goods.Goods.UpdateGoodsStocks:output_type -> goods.UpdateGoodsStocksResponse
	9,  // 21: goods.Goods.UpdateGoodsStocksRollback:output_type -> goods.UpdateGoodsStocksRollbackResponse
	12, // 22: goods.Goods.TCCTradingNum:output_type -> goods.TCCTradingNumResponse
	14, // 23: goods.Goods.TCCTradingLockNum:output_type -> goods.TCCTradingLockNumResponse
	16, // 24: goods.Goods.TCCTradingRollbackNum:output_type -> goods.TCCTradingRollbackNumResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_goods_proto_init() }
func file_goods_proto_init() {
	if File_goods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsByIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsByIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGoodsStocksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGoodsStocksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGoodsStocksRollbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGoodsStocksRollbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCCInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCCTradingNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCCTradingNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCCTradingLockNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCCTradingLockNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCCTradingRollbackNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCCTradingRollbackNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_proto_goTypes,
		DependencyIndexes: file_goods_proto_depIdxs,
		MessageInfos:      file_goods_proto_msgTypes,
	}.Build()
	File_goods_proto = out.File
	file_goods_proto_rawDesc = nil
	file_goods_proto_goTypes = nil
	file_goods_proto_depIdxs = nil
}
