// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package goodsclient

import (
	"context"

	"goods/goods"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGoodsByIDsRequest              = goods.GetGoodsByIDsRequest
	GetGoodsByIDsResponse             = goods.GetGoodsByIDsResponse
	GoodsInfo                         = goods.GoodsInfo
	Request                           = goods.Request
	Response                          = goods.Response
	TCCInfo                           = goods.TCCInfo
	TCCTradingLockNumRequest          = goods.TCCTradingLockNumRequest
	TCCTradingLockNumResponse         = goods.TCCTradingLockNumResponse
	TCCTradingNumRequest              = goods.TCCTradingNumRequest
	TCCTradingNumResponse             = goods.TCCTradingNumResponse
	TCCTradingRollbackNumRequest      = goods.TCCTradingRollbackNumRequest
	TCCTradingRollbackNumResponse     = goods.TCCTradingRollbackNumResponse
	UpdateGoodsStocksRequest          = goods.UpdateGoodsStocksRequest
	UpdateGoodsStocksResponse         = goods.UpdateGoodsStocksResponse
	UpdateGoodsStocksRollbackRequest  = goods.UpdateGoodsStocksRollbackRequest
	UpdateGoodsStocksRollbackResponse = goods.UpdateGoodsStocksRollbackResponse
	UpdateStockReq                    = goods.UpdateStockReq

	Goods interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		GetGoodsByIDs(ctx context.Context, in *GetGoodsByIDsRequest, opts ...grpc.CallOption) (*GetGoodsByIDsResponse, error)
		UpdateGoodsStocks(ctx context.Context, in *UpdateGoodsStocksRequest, opts ...grpc.CallOption) (*UpdateGoodsStocksResponse, error)
		UpdateGoodsStocksRollback(ctx context.Context, in *UpdateGoodsStocksRollbackRequest, opts ...grpc.CallOption) (*UpdateGoodsStocksRollbackResponse, error)
		// TCC
		TCCTradingNum(ctx context.Context, in *TCCTradingNumRequest, opts ...grpc.CallOption) (*TCCTradingNumResponse, error)
		TCCTradingLockNum(ctx context.Context, in *TCCTradingLockNumRequest, opts ...grpc.CallOption) (*TCCTradingLockNumResponse, error)
		TCCTradingRollbackNum(ctx context.Context, in *TCCTradingRollbackNumRequest, opts ...grpc.CallOption) (*TCCTradingRollbackNumResponse, error)
	}

	defaultGoods struct {
		cli zrpc.Client
	}
)

func NewGoods(cli zrpc.Client) Goods {
	return &defaultGoods{
		cli: cli,
	}
}

func (m *defaultGoods) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultGoods) GetGoodsByIDs(ctx context.Context, in *GetGoodsByIDsRequest, opts ...grpc.CallOption) (*GetGoodsByIDsResponse, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.GetGoodsByIDs(ctx, in, opts...)
}

func (m *defaultGoods) UpdateGoodsStocks(ctx context.Context, in *UpdateGoodsStocksRequest, opts ...grpc.CallOption) (*UpdateGoodsStocksResponse, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.UpdateGoodsStocks(ctx, in, opts...)
}

func (m *defaultGoods) UpdateGoodsStocksRollback(ctx context.Context, in *UpdateGoodsStocksRollbackRequest, opts ...grpc.CallOption) (*UpdateGoodsStocksRollbackResponse, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.UpdateGoodsStocksRollback(ctx, in, opts...)
}

// TCC
func (m *defaultGoods) TCCTradingNum(ctx context.Context, in *TCCTradingNumRequest, opts ...grpc.CallOption) (*TCCTradingNumResponse, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.TCCTradingNum(ctx, in, opts...)
}

func (m *defaultGoods) TCCTradingLockNum(ctx context.Context, in *TCCTradingLockNumRequest, opts ...grpc.CallOption) (*TCCTradingLockNumResponse, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.TCCTradingLockNum(ctx, in, opts...)
}

func (m *defaultGoods) TCCTradingRollbackNum(ctx context.Context, in *TCCTradingRollbackNumRequest, opts ...grpc.CallOption) (*TCCTradingRollbackNumResponse, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.TCCTradingRollbackNum(ctx, in, opts...)
}
