// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gateWay/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/notif",
				Handler: OrderNotifHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: OrderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Goods/TCCTradingNumTry",
				Handler: TCCTradingNumTryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Goods/TCCTradingNumConfirm",
				Handler: TCCTradingNumConfirmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Goods/TCCTradingNumCancel",
				Handler: TCCTradingNumCancelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Goods/TCCBalanceNumTry",
				Handler: TCCBalanceNumTryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Goods/TCCBalanceNumConfirm",
				Handler: TCCBalanceNumConfirmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Goods/TCCBalanceNumCancel",
				Handler: TCCBalanceNumCancelHandler(serverCtx),
			},
		},
	)
}
