// Code generated by goctl. DO NOT EDIT.
package types

type OrderNotifRequest struct {
}

type OrderNotifResponse struct {
	Message string `json:"message"`
}

type Goods struct {
	GoodID int64 `json:"good_id"`
	Num    int64 `json:"num"`
}

type CreateOrderRequest struct {
	UserID int64   `json:"user_id"`
	Goods  []Goods `json:"goods"`
}

type CreateOrderResponse struct {
	Url string `json:"url"`
}

type TCCInfo struct {
	GoodID int64 `json:"good_id"`
	Num    int64 `json:"num"`
}

type TCCTradingNumTry struct {
	UserID   int64     `json:"user_id"`
	TCCInfos []TCCInfo `json:"tcc_infos"`
}

type TCCTradingNumConfirm struct {
	UserID   int64     `json:"user_id"`
	TCCInfos []TCCInfo `json:"tcc_infos"`
}

type TCCTradingNumCancel struct {
	UserID   int64     `json:"user_id"`
	TCCInfos []TCCInfo `json:"tcc_infos"`
}

type TCCBalanceNumTryRequest struct {
	UserID int64 `json:"user_id"`
}

type TCCBalanceNumConfirmRequest struct {
	OrderNo string `json:"order_no"`
}

type TCCBalanceNumCancelRequest struct {
	OrderNo string `json:"order_no"`
}

type TCCBalanceNumTryResponse struct {
	ID int64 `json:"id"`
}

type TCCBalanceNumConfirmResponse struct {
	OrderNo string `json:"order_no"`
}

type TCCBalanceNumCancelResponse struct {
	OrderNo string `json:"order_no"`
}
