// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package orderclient

import (
	"context"

	"order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderGoodsRequest         = order.CreateOrderGoodsRequest
	CreateOrderGoodsResponse        = order.CreateOrderGoodsResponse
	CreateOrderRequest              = order.CreateOrderRequest
	CreateOrderResponse             = order.CreateOrderResponse
	GetOrderGoodsByOrderIDRequest   = order.GetOrderGoodsByOrderIDRequest
	GetOrderGoodsByOrderIDResponse  = order.GetOrderGoodsByOrderIDResponse
	GetOrderRequest                 = order.GetOrderRequest
	GetOrderResponse                = order.GetOrderResponse
	GetOrderRollbackRequest         = order.GetOrderRollbackRequest
	GetOrderRollbackResponse        = order.GetOrderRollbackResponse
	OrderGoodsInfo                  = order.OrderGoodsInfo
	OrderInfo                       = order.OrderInfo
	Request                         = order.Request
	Response                        = order.Response
	TCCTradingLockOrderRequest      = order.TCCTradingLockOrderRequest
	TCCTradingLockOrderResponse     = order.TCCTradingLockOrderResponse
	TCCTradingOrderRequest          = order.TCCTradingOrderRequest
	TCCTradingOrderResponse         = order.TCCTradingOrderResponse
	TCCTradingRollbackOrderRequest  = order.TCCTradingRollbackOrderRequest
	TCCTradingRollbackOrderResponse = order.TCCTradingRollbackOrderResponse
	UpdateOrderRequest              = order.UpdateOrderRequest
	UpdateOrderResponse             = order.UpdateOrderResponse

	Order interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		GetOrderRollback(ctx context.Context, in *GetOrderRollbackRequest, opts ...grpc.CallOption) (*GetOrderRollbackResponse, error)
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
		UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error)
		CreateOrderGoods(ctx context.Context, in *CreateOrderGoodsRequest, opts ...grpc.CallOption) (*CreateOrderGoodsResponse, error)
		GetOrderGoodsByOrderID(ctx context.Context, in *GetOrderGoodsByOrderIDRequest, opts ...grpc.CallOption) (*GetOrderGoodsByOrderIDResponse, error)
		// TCC
		TCCTradingOrder(ctx context.Context, in *TCCTradingOrderRequest, opts ...grpc.CallOption) (*TCCTradingOrderResponse, error)
		TCCTradingLockOrder(ctx context.Context, in *TCCTradingLockOrderRequest, opts ...grpc.CallOption) (*TCCTradingLockOrderResponse, error)
		TCCTradingRollbackOrder(ctx context.Context, in *TCCTradingRollbackOrderRequest, opts ...grpc.CallOption) (*TCCTradingRollbackOrderResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrderRollback(ctx context.Context, in *GetOrderRollbackRequest, opts ...grpc.CallOption) (*GetOrderRollbackResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderRollback(ctx, in, opts...)
}

func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrder) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.UpdateOrder(ctx, in, opts...)
}

func (m *defaultOrder) CreateOrderGoods(ctx context.Context, in *CreateOrderGoodsRequest, opts ...grpc.CallOption) (*CreateOrderGoodsResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrderGoods(ctx, in, opts...)
}

func (m *defaultOrder) GetOrderGoodsByOrderID(ctx context.Context, in *GetOrderGoodsByOrderIDRequest, opts ...grpc.CallOption) (*GetOrderGoodsByOrderIDResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderGoodsByOrderID(ctx, in, opts...)
}

// TCC
func (m *defaultOrder) TCCTradingOrder(ctx context.Context, in *TCCTradingOrderRequest, opts ...grpc.CallOption) (*TCCTradingOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TCCTradingOrder(ctx, in, opts...)
}

func (m *defaultOrder) TCCTradingLockOrder(ctx context.Context, in *TCCTradingLockOrderRequest, opts ...grpc.CallOption) (*TCCTradingLockOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TCCTradingLockOrder(ctx, in, opts...)
}

func (m *defaultOrder) TCCTradingRollbackOrder(ctx context.Context, in *TCCTradingRollbackOrderRequest, opts ...grpc.CallOption) (*TCCTradingRollbackOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TCCTradingRollbackOrder(ctx, in, opts...)
}
